---
- name: Check if fingerprint authentication in terminal is enabled
  ansible.builtin.command:
    grep -E "^auth\s+sufficient\s+pam_tid.so$" "/etc/pam.d/sudo"
  register: auth_enabled
  changed_when: false
  failed_when: false

- name: Enable support for fingerprint authentication in terminal
  when: auth_enabled.rc != 0
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sudo
    insertafter: "^# sudo: auth account password session"
    line: auth sufficient pam_tid.so
    backup: true
  become: true
  become_method: ansible.builtin.sudo
