---
- name: Copy shell files
  ansible.builtin.copy:
    src: "{{ shell_file }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ shell_file }}"
    mode: "0644"
    force: false
  loop:
    - .zshrc
    - .zprofile
  loop_control:
    loop_var: shell_file
    label: copy {{ shell_file }}

- name: Create generated shell files
  ansible.builtin.template:
    src: "{{ shell_file }}.j2"
    dest: "{{ ansible_env.HOME }}/{{ shell_file }}"
    mode: "0644"
  loop:
    - .generated.zshrc
    - .generated.zprofile
  loop_control:
    loop_var: shell_file
    label: generate {{ shell_file }}
