---
- name: Install ZShell
  community.general.homebrew:
    name:
      - zsh
      - starship
    state: present

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_stat

- name: Install Oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: command_result
  when: not ohmyzsh_stat.stat.exists
  changed_when: command_result.rc == 0
  failed_when: command_result.rc != 0

- name: Install syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ shell_ohmyzsh_plugins_path }}/zsh-syntax-highlighting"
    clone: true
    update: true
    version: master

- name: Install autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ shell_ohmyzsh_plugins_path }}/zsh-autosuggestions"
    clone: true
    update: true
    version: master

- name: Generate .zshrc file
  ansible.builtin.template:
    src: .zshrc.j2
    dest: '{{ ansible_env.HOME }}/.zshrc'
    mode: '0644'

- name: Copy .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: "{{ ansible_env.HOME }}/.zprofile"
    mode: '0644'
