---
- name: Include fingerprint PAM enablement
  ansible.builtin.include_tasks: enable-fingerprint-pam.yml

- name: Include ZShell setup
  ansible.builtin.include_tasks: setup-zsh.yml

- name: Include OhMyZsh Setup
  ansible.builtin.include_tasks: setup-ohmyzsh.yml

- name: Setup Starship
  ansible.builtin.include_tasks: setup-starship.yml
