---
- name: Install ZShell
  community.general.homebrew:
    name:
      - zsh
      - starship
    state: latest

- name: Get ZShell binary location
  ansible.builtin.shell: echo "$(brew --prefix zsh)/bin/zsh"
  register: zsh_bin_result
  changed_when: false
  failed_when: zsh_bin_result.rc != 0

- name: Add ZShell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ zsh_bin_result.stdout }}"
    state: present
  become: true

- name: Set ZShell as the default shell.
  ansible.builtin.command: >
    chsh -s {{ zsh_bin_result.stdout }} {{ ansible_env.USER }}
  register: chsh_result
  changed_when: false
  failed_when: chsh_result.rc != 0
  become: true
  become_method: ansible.builtin.sudo
