---
- name: Install Starship
  community.general.homebrew:
    name: starship
    state: latest

- name: Enable Startship via shell initialization.
  vars:
    section:
      name: Enable Starship.
      content: eval "$(starship init zsh)"
  ansible.builtin.set_fact:
    shell_zshrc_sections:
      "{{ shell_zshrc_sections | default([]) + [section] }}"
