---
- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_stat

- name: Install Oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: install_ohmyzsh_result
  when: not ohmyzsh_stat.stat.exists
  changed_when: install_ohmyzsh_result.rc == 0
  failed_when: install_ohmyzsh_result.rc != 0

- name: Install syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ shell_ohmyzsh_plugins_path }}/zsh-syntax-highlighting"
    clone: true
    update: true
    version: master

- name: Install autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ shell_ohmyzsh_plugins_path }}/zsh-autosuggestions"
    clone: true
    update: true
    version: master
