---
- name: Setup personal machine
  hosts: localhost
  roles:
    - role: homebrew
    - role: iterm2
    - role: java
    - role: microk8s
    - role: haskell
    - role: nodejs

    - role: git
      vars:
        git_user_name: Idan Or
        git_user_email: idan.or@outlook.com

    - role: python
      vars:
        python_global_version: "3.11"
        python_versions:
          - "3.11"
          - "3.9"

    - role: tools
      vars:
        tools_taps:
          - teamookla/speedtest

        tools_formulas:
          - mas
          - tmux
          - jq
          - thefuck
          - tldr
          - speedtest
          - q
          - bat
          - fx
          - rustup
          - dive # move to cloud role
          - k9s # move to cloud role

        tools_casks:
          - google-chrome
          - whatsapp
          - zoom
          - messenger
          - telegram
          - vlc
          - microsoft-office
          - visual-studio-code
          - jetbrains-toolbox
          - numi
          - postman
          - anydesk
          - steam
          # - warp
          # - raycast
          # - arc
          # TODO: move to cloud role:
          - lens

        tools_app:
          - Paste - Endless Clipboard

    # This must be last!
    - role: shell
      vars:
        shell_ohmyzsh_plugins:
          - name: aliases
          - name: alias-finder
          - name: jump
          - name: wd
          - name: zsh-autosuggestions
            formula: zsh-autosuggestions
          - name: zsh-syntax-highlighting
            formula: zsh-syntax-highlighting
          # TODO: move to cloud role:
          - name: helm
          - name: docker
          - name: kubectl
