---
- name: Setup personal machine
  hosts: localhost
  roles:
    - role: homebrew
    - role: java
    - role: haskell
    - role: nodejs

    - role: microk8s
      vars:
        microk8s_addons:
          - name: dns
          - name: registry

    - role: iterm2
      vars:
        iterm2_advanced_configs:
          AlternateMouseScroll: "1"
          BootstrapDaemon: "0"

    - role: git
      vars:
        git_user_name: Idan Or
        git_user_email: idan.or@outlook.com
        git_aliases:
          unstage: reset HEAD --
          decommit: reset HEAD~1 --soft
          ignore: "!gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi"
          tfo: "!f() { git checkout -b idan-emergency-exit && git add -A && git commit -m \"Emergency exit\" && git push origin head -u -f; }; f"
          lazy: "!l() { git commit -a -m \"$*\"; git push; }; l"
          count-lines: >-
            ! git log --author=\"$1\" --pretty=tformat: --numstat |
            awk '{ add += $1; subs += $2; loc += $1 - $2 } END
            { printf \"added lines: %s, removed lines: %s,
            total lines: %s\\n\", add, subs, loc }'

    - role: python
      vars:
        python_global_version: "3.11"
        python_versions:
          - "3.11"
          - "3.9"

    - role: tools
      vars:
        tools_taps:
          - teamookla/speedtest

        tools_formulas:
          - mas
          - tmux
          - jq
          - thefuck
          - tldr
          - speedtest
          - q
          - bat
          - fx
          - rustup
          - dive # move to cloud role
          - k9s # move to cloud role

        tools_casks:
          - google-chrome
          - whatsapp
          - zoom
          - messenger
          - telegram
          - vlc
          - microsoft-office
          - visual-studio-code
          - jetbrains-toolbox
          - numi
          - postman
          - anydesk
          - steam
          # - warp
          # - raycast
          # - arc
          # TODO: move to cloud role:
          - lens

        tools_app:
          - Paste - Endless Clipboard

    # This must be last!
    - role: shell
      vars:
        shell_zsh_aliases:
          zshconfig: $EDITOR $HOME/.zshrc
          ohmyzsh: $EDITOR $HOME/.oh-my-zsh
          reload: exec $shell

        shell_ohmyzsh_plugins:
          - name: aliases
          - name: alias-finder
          - name: jump
          - name: wd
          - name: zsh-autosuggestions
            formula: zsh-autosuggestions
          - name: zsh-syntax-highlighting
            formula: zsh-syntax-highlighting
          # TODO: move to cloud role:
          - name: helm
          - name: docker
          - name: kubectl
