---
- name: Apply roles
  hosts: localhost
  roles:
    - role: homebrew
    # - role: git
    - role: shell
    - role: iterm2
    # - role: tools
    # - role: apps
    - role: python
    - role: java
