---
- name: Apply roles
  hosts: localhost
  roles:
    # - role: homebrew
    # - role: git
    # - role: shell
    # - role: tools
    # - role: apps
    # - role: java
    # - role: iterm2
    - role: python
