---
- name: Generate kubeconfig
  ansible.builtin.command: microk8s config
  register: kubeconfig
  changed_when: false
  failed_when: kubeconfig.rc != 0

# TODO: does .kube folder exist?
- name: Save kubeconfig in .kube directory
  ansible.builtin.copy:
    content: "{{ kubeconfig.stdout }}"
    dest: "{{ microk8s_kubeconfig }}"
    mode: "0600"
