---
- name: Generate kubeconfig
  ansible.builtin.command: microk8s config
  register: kubeconfig
  changed_when: false
  failed_when: kubeconfig.rc != 0

- name: Create .kube directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0755'

- name: Save kubeconfig in .kube directory
  ansible.builtin.copy:
    content: "{{ kubeconfig.stdout }}"
    dest: "{{ microk8s_kubeconfig }}"
    mode: "0600"
