---
- name: Include MicroK8s installation
  ansible.builtin.include_tasks: install-microk8s.yml

- name: Include addons enablement
  ansible.builtin.include_tasks: enable-addons.yml
  when: microk8s_addons | length > 0

- name: Include dashboard enablement
  ansible.builtin.include_tasks: enable-dashboard.yml
  when: microk8s_dashbaord_enabled

- name: Include kubeconfig generation
  ansible.builtin.include_tasks: export-kubeconfig.yml
  when: microk8s_export_kubeconfig

- name: Include multipass alias generation
  ansible.builtin.include_tasks: create-aliases.yml
  when: microk8s_aliases | length > 0
