---
- name: Install PyEnv
  community.general.homebrew:
    name: pyenv
    state: latest

- name: Enable PyEnv in shell
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} Enable PyEnv."
    block: |
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'
    append_newline: true
