---
- name: Detect Poetry installation
  ansible.builtin.command: which poetry
  register: which_poetry_result
  changed_when: false
  failed_when: false

- name: Install Poetry
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -sSL https://install.python-poetry.org | python -
  register: poetry_install_result
  changed_when: poetry_install_result.rc == 0
  failed_when: poetry_install_result.rc != 0
  when: which_poetry_result.rc != 0
  # noqa: command-instead-of-module

- name: Check if Poetry terminal completion is enabled.
  ansible.builtin.stat:
    path: "{{ shell_ohmyzsh_plugins_path }}/poetry/_poetry"
  register: pyenv_completion_exists

- name: Enable Poetry terminal completion
  ansible.builtin.shell: >
    mkdir -p {{ shell_ohmyzsh_plugins_path }}/poetry &&
    poetry completions zsh > {{ shell_ohmyzsh_plugins_path }}/poetry/_poetry
  register: pyenv_completions_result
  when: pyenv_completion_exists.stat.exists
  changed_when: pyenv_completions_result.rc != 0
  failed_when: pyenv_completions_result.rc != 0
