---
- name: Detect Poetry installation
  ansible.builtin.command: which poetry
  register: which_poetry
  changed_when: false
  failed_when: false

- name: Install Poetry
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -sSL https://install.python-poetry.org | python -
  register: poetry_install
  changed_when: poetry_install.rc == 0
  failed_when: poetry_install.rc != 0
  when: which_poetry.rc != 0
  # noqa: command-instead-of-module

- name: Enable Poetry
  ansible.builtin.blockinfile:
    dest: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} Enable Poetry."
    block: export PATH=$HOME/.local/bin:$PATH
    append_newline: true

- name: Check if Poetry terminal completion is enabled.
  ansible.builtin.stat:
    path: "{{ shell_zsh_plugins_path }}/poetry/_poetry"
  register: pyenv_completion_exists

- name: Enable Poetry terminal completion
  ansible.builtin.shell: >
    mkdir -p {{ shell_zsh_plugins_path }}/poetry &&
    poetry completions zsh > {{ shell_zsh_plugins_path }}/poetry/_poetry
  register: pyenv_completions
  when: pyenv_completion_exists.stat.exists
  changed_when: pyenv_completions.rc != 0
  failed_when: pyenv_completions.rc != 0
