---
- name: Install Python versions
  ansible.builtin.command: pyenv install {{ python_version }}
  register: pyenv_install
  changed_when: pyenv_install.rc == 0
  failed_when: >
    pyenv_install.rc != 0 and
    'already exists' not in pyenv_install.stderr
  loop: "{{ python_versions }}"
  loop_control:
    loop_var: python_version
    label: Installing Python {{ python_version }}

- name: Detect current global Python version
  ansible.builtin.command: pyenv global
  register: pyenv_get_global
  changed_when: false
  ignore_errors: true

- name: Set global Python version
  when: pyenv_get_global.stdout != python_global_version
  ansible.builtin.command: pyenv global {{ python_global_version }}
  register: pyenv_set_global
  changed_when: pyenv_set_global.rc == 0
  failed_when: pyenv_set_global.rc != 0
