---
# List of MicroK8s addons to enable.
microk8s_addons:
  - dns
  - registry

# Whether to enable K8s dashbaord.
microk8s_dashbaord_enabled: true

# Whether to export kubeconfig file.
microk8s_export_kubeconfig: true
