---
# Path to OhMyZsh custom directory.
shell_ohmyzsh_custom_dir: "{{ lookup('env', 'ZSH_CUSTOM') | default('~/.oh-my-zsh/custom', true) }}"

# Path to OhMyZsh plugins directory.
shell_ohmyzsh_plugins_dir: "{{ shell_ohmyzsh_custom_dir }}/plugins"

# List of all plugins to load.
shell_ohmyzsh_all_plugins: >-
  {{
    shell_ohmyzsh_plugins +
    shell_ohmyzsh_extra_plugins
  }}
