---
- name: Install jEnv
  community.general.homebrew:
    name: jenv
    state: latest

- name: Enable jEnv in shell
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    marker: "# {mark} Enable JEnv."
    block: |
      export PATH="$HOME/.jenv/bin:$PATH"
      eval "$(jenv init -)"
    append_newline: true

- name: Enabled $JAVA_HOME auto-export
  ansible.builtin.shell: eval $(jenv init -) && jenv enable-plugin export
  register: jenv_export
  changed_when: "'already enabled' not in jenv_export.stdout"
  failed_when: jenv_export.rc != 0
