---
- name: Install JDK versions
  community.general.homebrew:
    name: "{{ jdks }}"
    state: present

- name: Register JDK versions with jEnv
  ansible.builtin.shell:
    cmd: jenv add $(brew --prefix {{ item }})
  loop: "{{ jdks }}"
  failed_when: verify.rc != 0

- name: Set global JDK
  ansible.builtin.shell:
    cmd: "jenv global {{ global_jdk }}"

- name: Export flags for global JDK.
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    marker: "# {mark} Set flags for JDK."
    block: 'export CPPFLAGS="-I$(jenv prefix)/include"'
    insertbefore: "^# Start Starship \\(THIS MUST BE LAST!\\)\\.$"
    append_newline: true