---
- name: Install jEnv
  community.general.homebrew:
    state: latest
    name: jenv

- name: Enable jEnv in shell
  vars:
    section:
      name: Enable JEnv.
      content: |-
        export PATH="$HOME/.jenv/bin:$PATH"
        eval "$(jenv init -)"
      interactive_only: false
  ansible.builtin.set_fact:
    shell_init_sections:
      "{{ shell_init_sections | default([]) + [section] }}"

- name: Enabled $JAVA_HOME auto-export
  ansible.builtin.command: jenv sh-enable-plugin export
  register: jenv_export
  changed_when: "'already enabled' not in jenv_export.stdout"
  failed_when: jenv_export.rc != 0
