---
- name: Install jEnv
  community.general.homebrew:
    name: jenv
    state: present

- name: Enable jEnv in shell
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    marker: "# {mark} Enable JEnv."
    block: eval "$(jenv init -)"
    insertbefore: "^# Start Starship \\(THIS MUST BE LAST!\\)\\.$"
    append_newline: true
  # TODO: check if succeeded

- name: Enabled $JAVA_HOME auto-export
  ansible.builtin.shell:
    cmd: jenv enable-plugin export