---
- name: Get current global JDK
  ansible.builtin.command: jenv global
  register: jenv_get_global
  changed_when: false

- name: Determine new global JDK version
  ansible.builtin.shell: |
    set -o pipefail;
    brew list --version {{ java_global_jdk }} | awk '{print $2}'
  register: global_jdk_version
  changed_when: false

- name: Set global JDK
  when: global_jdk_version.stdout != jenv_get_global.stdout
  ansible.builtin.command: jenv global {{ global_jdk_version.stdout }}
  register: jenv_set_global
  changed_when: jenv_set_global.rc == 0
  failed_when: jenv_set_global.rc != 0

- name: Export flags for global JDK
  vars:
    section:
      name: Set flags for JDK.
      content: export CPPFLAGS="-I$(jenv prefix)/include"
      interactive: false
  ansible.builtin.set_fact:
    shell_init_sections:
      "{{ shell_init_sections | default([]) + [section] }}"
