---
- name: Install Rosetta
  ansible.builtin.command: softwareupdate --install-rosetta --agree-to-license
  register: jenv_global
  changed_when: false
  failed_when: jenv_global.rc != 0

- name: Install formulas
  community.general.homebrew:
    name: "{{ tools_formulas }}"
    state: latest

- name: Install casks
  community.general.homebrew_cask:
    name: "{{ tools_casks }}"
    state: latest
