---
- name: Install Formulas
  community.general.homebrew:
    name: "{{ tools_formulas }}"
    state: present

- name: Install Casks
  community.general.homebrew_cask:
    name: "{{ tools_casks }}"
    state: present
