---
- name: Detect current configuration of '{{ iterm_config.key }}'
  ansible.builtin.command:
    defaults read {{ iterm2_plist_file | quote }} {{ iterm_config.key | quote }}
  register: iterm_config_current_value
  ignore_errors: true
  changed_when: false

- name: Set value of '{{ iterm_config.key }}'
  when: iterm_config.value != iterm_config_current_value.stdout
  ansible.builtin.shell: >
    defaults write {{ iterm2_plist_file | quote }}
    {{ iterm_config.key | quote }} {{ iterm_config.value | quote }}
  register: default_write
  changed_when: default_write.rc == 0
  failed_when: default_write.rc != 0
