---
- name: Install formulas
  community.general.homebrew:
    state: latest
    name: multipass

- name: Enable multipass aliases in shell
  vars:
    section:
      name: Enable multipass aliases.
      content: export PATH="{{ multipass_alias_dir }}:$PATH"
      interactive_only: false
  ansible.builtin.set_fact:
    shell_init_sections:
      "{{ shell_init_sections | default([]) + [section] }}"