---
- name: Setup SolarEdge machine
  hosts: solaredge
  roles:
    - role: homebrew
    - role: iterm2
    - role: java

    - role: git
      vars:
        git_user_name: Idan Asraf
        git_user_email: idan.asraf@solaredge.com

    - role: python
      vars:
        python_global_version: "3.9"
        python_versions:
          - "3.10"
          - "3.9"
          - "3.7"

    - role: tools
      vars:
        tools_formulas:
          - mas
          - tmux
          - jq
          - thefuck
          - tldr
          - speedtest
          - q
          - bat
          - fx
          - awscli # move to cloud role
          - eksctl # move to cloud role
          - dive # move to cloud role
          - k9s # move to cloud role

        tools_casks:
          - google-chrome
          - whatsapp
          - zoom
          - messenger
          - vlc
          - microsoft-office
          - visual-studio-code
          - jetbrains-toolbox
          - numi
          - postman
          - anydesk
          # - warp
          # - raycast
          # - arc
           # TODO: move to cloud role
          - docker
          - lens

    - role: shell
      vars:
        shell_ohmyzsh_plugins:
          - name: aliases
          - name: alias-finder
          - name: jump
          - name: wd
          # TODO: move to cloud role
          - name: helm
          - name: docker
          - name: kubectl
          - name: aws
