---
# TODO: is this created before first run?
iterm2_plist_path: "{{ ansible_env.HOME }}/Library/Preferences/com.googlecode.iterm2.plist"
iterm2_dynamic_profiles_dir: "{{ ansible_env.HOME }}/Library/Application\ Support/iTerm2/DynamicProfiles"
iterm2_profile_guid: >
  {{
  lookup('file', 'Profiles.json') |
  from_json |
  community.general.json_query("Profiles[?(@.Name == 'Idan')].Guid") |
  first
  }}
