---
# TODO: is this created before first run?
# Path to iTerm2's configuration .plist file.
iterm2_plist_path: "{{ ansible_env.HOME }}/Library/Preferences/com.googlecode.iterm2.plist"

# Path to iTerm2's dynamic profiles directory.
iterm2_dynamic_profiles_dir: "{{ ansible_env.HOME }}/Library/Application\ Support/iTerm2/DynamicProfiles"

# TODO: profile name should be take from variables.
# Guid of iTerm2 profile to be set as default.
iterm2_default_profile_guid: >-
  {{
  lookup('file', 'Profiles.json') |
  from_json |
  community.general.json_query("Profiles[?(@.Name == 'Idan')].Guid") |
  first
  }}
