---
- name: Install Starship
  community.general.homebrew:
    name: starship
    state: latest

- name: Enable Startship in .zshrc
  vars:
    section:
      name: Enable Starship (THIS MUST BE LAST!)
      content: eval "$(starship init zsh)"
  ansible.builtin.set_fact:
    shell_zshrc_sections:
      "{{ shell_zshrc_sections | default([]) + [section] }}"
